# Generated by Django 3.2.9 on 2021-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=250)),
                ('links', models.CharField(max_length=100)),
                ('images', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='images',
        ),
        migrations.RemoveField(
            model_name='users',
            name='links',
        ),
    ]
