# Generated by Django 3.2.9 on 2021-11-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0003_auto_20211105_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='links',
            new_name='link',
        ),
    ]
