# Generated by Django 3.2.9 on 2021-11-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0004_rename_links_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='desc',
            field=models.TextField(default='No info About me', max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='No name', max_length=30),
        ),
    ]
